# Generated by Django 6.0.2 on 2026-02-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Médico'), ('reception', 'Recepção')], default='reception', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
