# Generated by Django 6.0.2 on 2026-02-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_clinicsettings'),
        ('doctors', '0002_alter_doctorprofile_agenda_color_and_more'),
        ('patients', '0003_alter_patient_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Início da Consulta')),
                ('end_datetime', models.DateTimeField(verbose_name='Fim da Consulta')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('done', 'Realizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Status da consulta')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic', verbose_name='Clínica')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctorprofile', verbose_name='Médico responsável')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['start_datetime'],
            },
        ),
    ]
