# Generated by Django 6.0.2 on 2026-02-16 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinicsettings'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='agenda_color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor da Agenda'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.clinic', verbose_name='Clínica'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='crm',
            field=models.CharField(max_length=20, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialty', verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Especialidade'),
        ),
        migrations.CreateModel(
            name='DoctorScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('slot_duration', models.PositiveIntegerField(blank=True, help_text='Duração da consulta em minutos', null=True)),
                ('allow_weekends', models.BooleanField(blank=True, help_text='Se null → usa configuração da clínica', null=True)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_settings', to='doctors.doctorprofile')),
            ],
        ),
    ]
